### ISSUE TITLE
Rename crate name "ring" to another one to avoid conflicting with briansmith/ring

### ISSUE THREAD

**Issue by jasl** [w3f/ring-proof#14]
I'm sorry, this idea feels rude, but since `ring` has already been taken by `briansmith/ring` and it's famous, and if a project has them both (like Substrate), Cargo will identify them as one crate, which will cause potential conflict.

**Comment by burdges** [comment]
Yeah, it cannot be published without being renamed, so that'll happen eventually.  web3sum-ring-proof or something like that.  Ain't my call on the name though.

**Comment by gilescope** [comment]
Was just looking to see why we had what looked like a really old version of ring in substrate and ended up here.

**Comment by swasilyev** [comment]
will be covered under https://github.com/w3f/ring-proof/issues/38
