### ISSUE TITLE
error[E0308]: arguments to this function are incorrect while building substrate

### ISSUE THREAD

**Issue by h4n0** [w3f/ring-proof#26]
Seems my substrate build was broken after cargo updated the `ring-proof` to `665f5f51`.

```
error[E0308]: arguments to this function are incorrect
   --> /Users/han/.cargo/git/checkouts/ring-vrf-fa8519651343a7ee/4b09416/bandersnatch_vrfs/src/ring.rs:85:9
    |
85  |         ring::index(self.pcs_params.clone(), &self.piop_params, pks).0
    |         ^^^^^^^^^^^
    |
note: expected `&_`, found `URS<Bls12<Config>>`
   --> /Users/han/.cargo/git/checkouts/ring-vrf-fa8519651343a7ee/4b09416/bandersnatch_vrfs/src/ring.rs:85:21
    |
```

It took me some time to identify and locate this, and my workaround is to downgrade it to the previous version by doing:
```
cargo update -p ring@0.1.0 --precise 626c9598
```

Please take a look at this issue.

**Comment by davxy** [comment]
This is not a ring-proof issue.
The issue is that `bandersnatch_vrfs` has this as a git dependency without specify a revision. I'm on it

**Comment by davxy** [comment]
Fixed by: https://github.com/w3f/ring-vrf/pull/92 and https://github.com/w3f/ring-vrf/pull/93
